version: "3.5"

services:
  passport:
    ports:
      - ${SERVICE_PORT}:8080
    environment:
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
    deploy:
      replicas: ${REPLICAS}
      restart_policy:
        condition: on-failure

networks:
  default:
    external:
      name: ${NETWORK_NAME}